# Generated by Django 4.1 on 2024-11-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0002_login_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login_Status',
        ),
    ]
