# Generated by Django 4.1 on 2024-11-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSystem', '0003_delete_login_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginsystem',
            old_name='password',
            new_name='passwords',
        ),
    ]
